import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

const repositoryRoot = path.resolve(import.meta.dirname, '../..');
const blueprintPath = path.join(repositoryRoot, 'config', 'deployment', 'render.yaml');
const dockerfilePath = path.join(repositoryRoot, 'apps', 'collab-server', 'Dockerfile');

test('Render collaboration deployment keeps secrets generated and SQLite durable', async () => {
  const blueprint = await readFile(blueprintPath, 'utf8');
  assert.match(blueprint, /runtime: docker/u);
  assert.match(blueprint, /dockerfilePath: \.\/apps\/collab-server\/Dockerfile/u);
  assert.match(blueprint, /healthCheckPath: \/healthz/u);
  assert.match(blueprint, /mountPath: \/data/u);
  assert.match(
    blueprint,
    /FORGEBOARD_COLLAB_DATABASE_PATH[\s\S]*\/data\/forgeboard-collab\.sqlite/u,
  );
  for (const secret of ['FORGEBOARD_COLLAB_SIGNING_KEY', 'FORGEBOARD_COLLAB_ADMIN_TOKEN']) {
    assert.match(
      blueprint,
      new RegExp(`key: ${secret}\\n\\s+generateValue: true`, 'u'),
      `${secret} must be generated by the host`,
    );
  }
  assert.doesNotMatch(blueprint, /FORGEBOARD_COLLAB_(?:SIGNING_KEY|ADMIN_TOKEN)\s*\n\s*value:/u);
});

test('production container accepts a platform port without weakening its non-root runtime', async () => {
  const dockerfile = await readFile(dockerfilePath, 'utf8');
  assert.doesNotMatch(dockerfile, /FORGEBOARD_COLLAB_PORT=/u);
  assert.match(dockerfile, /USER forgeboard/u);
  assert.match(dockerfile, /HEALTHCHECK[\s\S]*process\.env\.PORT/u);
});
