export {
  EXTENSION_API_VERSION,
  EXTENSION_MANIFEST_FILENAME,
  EXTENSION_RUNTIME_VERSION,
  CanvasNodeCapabilitySchema,
  CanvasNodeFieldSchema,
  CanvasNodePortSchema,
  CanvasNodeTypeManifestSchema,
  ExtensionApprovalSchema,
  ExtensionManifestSchema,
  ExtensionPermissionSchema,
  InstalledExtensionRecordSchema,
  SemanticVersionSchema,
  extensionNodeTypeId,
  parseExtensionManifest,
  requiredPermissionsForManifest,
  type CanvasNodeField,
  type CanvasNodeTypeManifest,
  type ExtensionApproval,
  type ExtensionManifest,
  type ExtensionPermission,
  type InstalledExtensionRecord,
} from './schema.js';
export {
  EXTENSION_APPROVAL_MAX_AGE_MS,
  EXTENSION_APPROVAL_MAX_FUTURE_SKEW_MS,
  ExtensionRuntimeError,
  LocalExtensionService,
  compareSemanticVersions,
  createExtensionApproval,
  type ExtensionDiscoveryResult,
  type ExtensionInstallPlan,
  type ExtensionRuntimeErrorCode,
  type InstalledExtension,
  type InvalidInstalledExtension,
} from './service.js';
